version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubygems:asciidoctor
    versions:
    - 2.0.12
    - 2.0.13
    - 2.0.14
