= JRuby Arquillian Adapter

This is an embedded http://arquillian.org[Arquillian] adapter that should simplify development with JRuby in combination with gems.
The adapter accepts `JavaArchive` deployments that contain gems.
It will automatically install the gems and inject properly configured `Ruby` and ScriptingContainer instances.

The following example shows a simple test that uses http://asciidoctor.org[Asciidoctor] directly via its Ruby interface to render a string.

.Example
[source,java]
----
package foo.test;

import org.arquillian.jruby.api.RubyScript;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.shrinkwrap.api.GenericArchive;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.FileAsset;
import org.jboss.shrinkwrap.api.asset.StringAsset;
import org.jboss.shrinkwrap.resolver.api.maven.Maven;
import org.jruby.Ruby;
import org.jruby.embed.ScriptingContainer;
import org.jruby.javasupport.JavaEmbedUtils;
import org.jruby.runtime.builtin.IRubyObject;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.File;

import static org.hamcrest.Matchers.containsString;
import static org.junit.Assert.assertNotSame;
import static org.junit.Assert.assertThat;

@RunWith(Arquillian.class)
public class BasicTest {

    @ArquillianResource // <1>
    private Ruby rubyInstance;

    @ArquillianResource // <1>
    private ScriptingContainer scriptingContainer;

    @Deployment
    public static GenericArchive deploy() throws Exception {
        File asciidoctorGem = Maven.configureResolver() // <2>
                .withRemoteRepo("rubygems", "http://rubygems-proxy.torquebox.org/releases", "default")
                .resolve("rubygems:asciidoctor:gem:1.5.2")
                .withTransitivity().asSingleFile();

        return ShrinkWrap.create(GenericArchive.class)
                .add(new FileAsset(asciidoctorGem), asciidoctorGem.getName())
                .add(new StringAsset("require 'asciidoctor'\n"), "requireasciidoctor.rb");
    }

    @Test
    public void shouldExecuteSimpleRubyStatement() throws Exception {

        IRubyObject result = rubyInstance.evalScriptlet(
                "java.lang.System.getProperties.map {|k,v| %(#{k}=#{v.inspect}) } * '\\n'");
        assertThat(
                (String)JavaEmbedUtils.rubyToJava(rubyInstance, result, String.class),
                containsString("java.io.tmpdir="));
    }

    @Test
    @RubyScript("requireasciidoctor.rb") // <3>
    public void shouldApplyScriptBeforeTest() throws Exception {

        IRubyObject result = rubyInstance.evalScriptlet(
                "Asciidoctor.convert '*This* is Asciidoctor.'");
        assertThat(
                (String)JavaEmbedUtils.rubyToJava(rubyInstance, result, String.class),
                containsString("<strong>This</strong> is Asciidoctor."));

    }
}
----
<1> `Ruby` and `ScriptingContainer` instances are by default created and injected per test, so that every method will get its own instance.
    To share an instance in all test methods add `@ApplicationScoped`.
<2> Gems can be resolved via the Maven resolver.
    Gem files are automatically installed in a temporary location by the container adapter and are available to the injected Ruby runtime.
<3> The script declared by the `@RubyScript` annotation is executed on the injected Ruby instance before the test.
    Here the script added to the deployment requires the asciidoctor gem and there makes invoking Asciidoctor possible.
    The annotation can also be defined on the test class.
    In this case first the scripts of the test class are executed before the scripts of the test method for each test method.

== Gem installation

As gem installation takes a considerable amount of time the adapter supports caching of previously installed caches.
Therefore you have to configure a cache directory where the adapter will store previously installed gems.

The following `arquillian.xml` will make the adapter cache gems:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.jboss.org/schema/arquillian http://www.jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <container qualifier="jrubyCached" default="true">
        <configuration>
            <property name="gemDir">build/cachedtestgems</property>
        </configuration>
    </container>

</arquillian>
----
