= JRuby Arquillian Adapter

This is an embedded http://arquillian.org[Arquillian] adapter that should simplify development with JRuby in combination with gems.
The adapter accepts `JavaArchive` deployments that contain gems.
It will automatically install the gems and inject properly configured `Ruby` and ScriptingContainer instances.

The following example shows a simple test that uses http://asciidoctor.org[Asciidoctor] directly via its Ruby interface to render a string.

.Example
[source,java]
----
package foo.test;

import org.arquillian.jruby.api.RubyResource;
import org.arquillian.jruby.api.RubyScript;
import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.arquillian.test.api.ArquillianResource;
import org.jboss.shrinkwrap.api.GenericArchive;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.FileAsset;
import org.jboss.shrinkwrap.api.asset.StringAsset;
import org.jboss.shrinkwrap.resolver.api.maven.Maven;
import org.jruby.Ruby;
import org.jruby.embed.ScriptingContainer;
import org.jruby.javasupport.JavaEmbedUtils;
import org.jruby.runtime.builtin.IRubyObject;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.File;

import static org.hamcrest.Matchers.containsString;
import static org.junit.Assert.assertNotSame;
import static org.junit.Assert.assertThat;

@RunWith(Arquillian.class)
public class BasicTest {

    @RubyResource // <1>
    private Ruby rubyInstance;

    @RubyResource // <1>
    private ScriptingContainer scriptingContainer;

    @Deployment
    public static GenericArchive deploy() throws Exception {
        File asciidoctorGem = Maven.configureResolver() // <2>
                .withRemoteRepo("rubygems", "http://rubygems-proxy.torquebox.org/releases", "default")
                .resolve("rubygems:asciidoctor:gem:1.5.2")
                .withoutTransitivity().asSingleFile();

        return ShrinkWrap.create(GenericArchive.class)
                .add(new FileAsset(asciidoctorGem), asciidoctorGem.getName())
                .add(new StringAsset("require 'asciidoctor'\n"), "requireasciidoctor.rb");
    }

    @Test
    public void shouldExecuteSimpleRubyStatement() throws Exception {

        IRubyObject result = rubyInstance.evalScriptlet(
                "java.lang.System.getProperties.map {|k,v| %(#{k}=#{v.inspect}) } * '\\n'");
        assertThat(
                (String)JavaEmbedUtils.rubyToJava(rubyInstance, result, String.class),
                containsString("java.io.tmpdir="));
    }

    @Test
    @RubyScript("requireasciidoctor.rb") // <3>
    public void shouldApplyScriptBeforeTest(@RubyResource Ruby rubyInstanceForTestMethod) throws Exception { // <4>

        IRubyObject result = rubyInstanceForTestMethod.evalScriptlet(
                "Asciidoctor.convert '*This* is Asciidoctor.'");
        assertThat(
                (String)JavaEmbedUtils.rubyToJava(rubyInstanceForTestMethod, result, String.class),
                containsString("<strong>This</strong> is Asciidoctor."));

    }
}
----
<1> Fields of type `Ruby` and `ScriptingContainer` instances annotated with `@RubyResource` are injected by the container.
    All test methods will see the same instances, that is the fields are injected once for the whole test class.
<2> Gems can be resolved via the Maven resolver.
    Gem files are automatically installed in a temporary location by the container adapter and are available to the injected Ruby runtime.
<3> The script declared by the `@RubyScript` annotation is executed on the `rubyInstanceForTestMethod` before the test.
    Here the script added to the deployment requires the asciidoctor gem and there makes invoking Asciidoctor possible.
<4> If a parameter to a test method is annotated with `@RubyResource` an own test method scoped instance is created for the test and passed.
    This is useful to have dedicated, clean Ruby instances per test.

== Gem installation

As gem installation takes a considerable amount of time the adapter supports caching of previously installed caches.
Therefore you have to configure a cache directory where the adapter will store previously installed gems.

The following `arquillian.xml` will make the adapter cache gems:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.jboss.org/schema/arquillian http://www.jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <container qualifier="jrubyCached" default="true">
        <configuration>
            <property name="gemDir">build/cachedtestgems</property>
        </configuration>
    </container>

</arquillian>
----

== Resource Injection

The container adapter knows to inject JRuby `ScriptingContainer` and `Ruby` instances.
It will handle all fields and test method parameters that are annotated with `@org.arquillian.jruby.api.RubyResource`.

Fields are injected once per test class so that all test methods share the same Ruby instance if they rely on the injected field.

Method parameters always get a new clean instance.

== Script execution

It is possible to apply scripts from the deployment archive before the test on the injected resources.
Therefore define the annotation `@org.arquillian.jruby.api.RubyScript` on the test class or the test method.
The annotation gets a list of ArchivePath names that must exist in the result of the deployment method.
Scripts defined in annotations on the class are executed before those of the test method.

Script annotations on the test class are handled before execution of _every_ test method.
After that script annotations on the test method are handled.

If the test method has an injected `ScriptingContainer` or `Ruby` as a method parameter.
Otherwise they are executed on the `ScriptingContainer` created for the test class.

== Ruby resource loading

By default the load path of the scripting container and the classloader is set to only load from the archive contents and the installed gems.
Therefore resources or test resources from the project are not available to the Ruby runtime unless you add them to the archive.

If your project already installs gems at build time it can make sense to do without this isolation and use the test classloader.
This can be configured in the container configuration using the property `isolatedClassloader`:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.jboss.org/schema/arquillian http://www.jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <container qualifier="isolated">
        <configuration>
            <property name="isolatedClassloader">true</property>
        </configuration>
    </container>

</arquillian>
----
